SELECT * FROM S;
SELECT * FROM J;
SELECT * FROM P;
SELECT * FROM SPJ;
SELECT SNO FROM SPJ WHERE JNO='J1';
SELECT SNO FROM SPJ WHERE JNO='J1' AND PNO='P1' ;
SELECT S.SNAME FROM S,SPJ WHERE S.SNO=SPJ.SNO AND SPJ.JNO='J1' AND PNO='P1';
SELECT SNAME FROM S WHERE SNO=(
 SELECT SNO FROM SPJ WHERE JNO='J1'
)
SELECT SNAME FROM S WHERE SNO=(
 SELECT SNO FROM SPJ WHERE JNO='J1' AND PNO='P1'
)
SELECT SNO FROM P,SPJ WHERE P.PNO=SPJ.PNO AND SPJ.JNO='J1' AND P.COLOR='∫Ï';
SELECT SNO FROM SPJ WHERE JNO=(
 SELECT JNO FROM J WHERE JNO='J1'
) AND PNO=(
 SELECT PNO FROM P WHERE COLOR='∫Ï'
)
UPDATE P SET COLOR='∫Ï' WHERE COLOR='ª∆'; 
SELECT SPJ.JNO FROM S,P,SPJ WHERE S.SNO=SPJ.SNO AND P.PNO=SPJ.PNO AND S.CITY <> 'ÃÏΩÚ' AND P.COLOR='∫Ï';
SELECT DISTINCT A.JNO  FROM SPJ A,SPJ B WHERE A.PNO=B.PNO AND A.SNO='S1';
INSERT INTO SPJ VALUES('S5','P2','J5',400);
INSERT INTO SPJ VALUES('S5','P4','J2',300);
SELECT P.PNAME FROM P,SPJ,S WHERE P.PNO=SPJ.PNO AND S.SNO=SPJ.SNO AND S.CITY='…œ∫£' ; 



